module.exports = [
    { "name": "Blizzard App", "path": "something" },
    { "name": "Dropbox", "path": "something" },
    { "name": "Google Chrome", "path": "something" },
    { "name": "League of Legends", "path": "something" },
    { "name": "Livestreamer 1.12.2", "path": "something" },
    { "name": "Nmap 7.60", "path": "something" },
    { "name": "Npcap 0.93", "path": "something" },
    { "name": "NVIDIA Stereoscopic 3D Driver", "path": "something" },
    { "name": "Open Broadcaster Software", "path": "something" },
    { "name": "Origin", "path": "something" },
    { "name": "Overwatch", "path": "something" },
    { "name": "Steam", "path": "something" },
    { "name": "Streamlink Twitch GUI", "path": "something" },
    { "name": "TeamViewer 12", "path": "something" },
    { "name": "XAMPP", "path": "something" },
    { "name": "vs_BlendMsi", "path": "something" },
    { "name": "vs_tipsmsi", "path": "something" },
    { "name": "Universal General MIDI DLS Extension SDK", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501", "path": "something" },
    { "name": "Dropbox Update Helper", "path": "something" },
    { "name": "Windows Software Development Kit - Windows 10.0.15063.468", "path": "something" },
    { "name": "vs_minshellmsi", "path": "something" },
    { "name": "Microsoft .NET CoreRuntime SDK", "path": "something" },
    { "name": "Microsoft .NET Native SDK", "path": "something" },
    { "name": "Windows SDK for Windows Store Apps Tools", "path": "something" },
    { "name": "Windows IP Over USB", "path": "something" },
    { "name": "Kits Configuration Installer", "path": "something" },
    { "name": "WinAppDeploy", "path": "something" },
    { "name": "Windows Team Extension SDK Contracts", "path": "something" },
    { "name": "Windows SDK", "path": "something" },
    { "name": "vs_filehandler_x86", "path": "something" },
    { "name": "WinRT Intellisense Desktop - Other Languages", "path": "something" },
    { "name": "Samsung Magician", "path": "something" },
    { "name": "Windows IoT Extension SDK", "path": "something" },
    { "name": "Windows App Certification Kit x64", "path": "something" },
    { "name": "Windows Phone SDK 8.0 Assemblies for Visual Studio 2017", "path": "something" },
    { "name": "Microsoft .NET Framework 4.6.1 SDK", "path": "something" },
    { "name": "icecap_collectionresourcesx64", "path": "something" },
    { "name": "Windows SDK AddOn", "path": "something" },
    { "name": "Microsoft Visual Studio Setup Configuration", "path": "something" },
    { "name": "Battlefield™ 1", "path": "something" },
    { "name": "Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030", "path": "something" },
    { "name": "vs_FileTracker_Singleton", "path": "something" },
    { "name": "WinRT Intellisense Desktop - en-us", "path": "something" },
    { "name": "LG Mobile Driver", "path": "something" },
    { "name": "vs_communitymsires", "path": "something" },
    { "name": "vs_clickoncesigntoolmsi", "path": "something" },
    { "name": "Microsoft .NET CoreRuntime For CoreCon", "path": "something" },
    { "name": "Universal CRT Headers Libraries and Sources", "path": "something" },
    { "name": "vs_communitymsi", "path": "something" },
    { "name": "Windows Simulator", "path": "something" },
    { "name": "Windows Team Extension SDK", "path": "something" },
    { "name": "Microsoft .NET Framework 4.5 Multi-Targeting Pack", "path": "something" },
    { "name": "Universal CRT Redistributable", "path": "something" },
    { "name": "vs_SQLClickOnceBootstrappermsi", "path": "something" },
    { "name": "Google Update Helper", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40660", "path": "something" },
    { "name": "Windows Mobile Connectivity Tools 10.0.15063.0 - Desktop x86", "path": "something" },
    { "name": "icecap_collectionresources", "path": "something" },
    { "name": "vs_minshellmsires", "path": "something" },
    { "name": "Microsoft Visual Studio 2017", "path": "something" },
    { "name": "Windows SDK for Windows Store Apps Metadata", "path": "something" },
    { "name": "Microsoft NetStandard SDK", "path": "something" },
    { "name": "icecap_collection_neutral", "path": "something" },
    { "name": "Windows SDK EULA", "path": "something" },
    { "name": "Windows App Certification Kit SupportedApiList x86", "path": "something" },
    { "name": "Windows SDK for Windows Store Apps Contracts", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40660", "path": "something" },
    { "name": "Universal CRT Tools x86", "path": "something" },
    { "name": "Microsoft Portable Library Multi-Targeting Pack", "path": "something" },
    { "name": "Microsoft Visual C++ 2005 Redistributable", "path": "something" },
    { "name": "Windows SDK for Windows Store Apps", "path": "something" },
    { "name": "WinRT Intellisense PPI - en-us", "path": "something" },
    { "name": "Windows IoT Extension SDK Contracts", "path": "something" },
    { "name": "League of Legends", "path": "something" },
    { "name": "Windows Desktop Extension SDK", "path": "something" },
    { "name": "Intellisense Lang Pack Mobile Extension SDK 10.0.15063.0", "path": "something" },
    { "name": "Windows SDK for Windows Store Managed Apps Libs", "path": "something" },
    { "name": "Visual C++ Library CRT Appx Package", "path": "something" },
    { "name": "Windows Desktop Extension SDK Contracts", "path": "something" },
    { "name": "Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161", "path": "something" },
    { "name": "Windows Simulator - ENU", "path": "something" },
    { "name": "windows_toolscorepkg", "path": "something" },
    { "name": "Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030", "path": "something" },
    { "name": "WinRT Intellisense IoT - en-us", "path": "something" },
    { "name": "Microsoft Portable Library Multi-Targeting Pack Language Pack - enu", "path": "something" },
    { "name": "Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030", "path": "something" },
    { "name": "vs_devenvmsi", "path": "something" },
    { "name": "WinRT Intellisense PPI - Other Languages", "path": "something" },
    { "name": "Microsoft Visual C++ 2017 Redistributable (x86) - 14.10.25008", "path": "something" },
    { "name": "vs_clickoncebootstrappermsires", "path": "something" },
    { "name": "vcpp_crt.redist.clickonce", "path": "something" },
    { "name": "Microsoft Visual C++ 2017 x86 Minimum Runtime - 14.10.25008", "path": "something" },
    { "name": "Visual C++ Library CRT Appx Package", "path": "something" },
    { "name": "Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030", "path": "something" },
    { "name": "WinRT Intellisense UAP - Other Languages", "path": "something" },
    { "name": "WinRT Intellisense IoT - Other Languages", "path": "something" },
    { "name": "TypeScript SDK", "path": "something" },
    { "name": "vs_minshellinteropmsi", "path": "something" },
    { "name": "Universal CRT Extension SDK", "path": "something" },
    { "name": "Microsoft UniversalWindowsPlatform SDK", "path": "something" },
    { "name": "Evernote v. 6.5.4", "path": "something" },
    { "name": "Sefaira for SketchUp", "path": "something" },
    { "name": "FLICK version 1.0.0.40", "path": "something" },
    { "name": "vs_clickoncebootstrappermsi", "path": "something" },
    { "name": "vs_filehandler_amd64", "path": "something" },
    { "name": "Twitch", "path": "something" },
    { "name": "Windows Mobile Extension SDK 10.0.15063.0 - ARM", "path": "something" },
    { "name": "Windows SDK Signing Tools", "path": "something" },
    { "name": "Microsoft ASP.NET Web Tools Packages 15.0 - ENU", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40660", "path": "something" },
    { "name": "ClickOnce Bootstrapper Package for Microsoft .NET Framework", "path": "something" },
    { "name": "Microsoft Visual C++ 2017 x86 Additional Runtime - 14.10.25008", "path": "something" },
    { "name": "Windows SDK Facade Windows WinMD Versioned", "path": "something" },
    { "name": "Microsoft ASP.NET Diagnostic Pack for Visual Studio", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660", "path": "something" },
    { "name": "TypeScript Power Tool", "path": "something" },
    { "name": "Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219", "path": "something" },
    { "name": "Microsoft System CLR Types for SQL Server 2017 CTP2.1", "path": "something" },
    { "name": "Intel(R) Processor Graphics", "path": "something" },
    { "name": "Realtek High Definition Audio Driver", "path": "something" },
    { "name": "Microsoft Visual C++ 2017 Redistributable (x64) - 14.10.25008", "path": "something" },
    { "name": "Visual C++ Library CRT Appx Resource Package", "path": "something" },
    { "name": "Windows SDK Modern Non-Versioned Developer Tools", "path": "something" },
    { "name": "WinRT Intellisense UAP - en-us", "path": "something" },
    { "name": "Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501", "path": "something" },
    { "name": "Windows SDK Modern Versioned Developer Tools", "path": "something" },
    { "name": "Microsoft Visual Studio Code", "path": "something" },
    { "name": "Windows Mobile Extension SDK 10.0.15063.0 - x86", "path": "something" },
    { "name": "VS Immersive Activate Helper", "path": "something" },
    { "name": "Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022", "path": "something" }
]